# Site settings
title: Happy Developers Sotware Solution
email: james.m@auswideweb.com.au
description: ""
twitter_username: jimilne
github_username:  shakna-israel
web_description:
designer: James Milne
baseurl: "http://shakna-israel.github.io/hdss/"

#Social Media -->
#Leave blank to hide

#facebook name
facebook:

#Google ID number
google:

#Twitter Username
twitter:

#LinkedIn ID
linkedin:

#Dribble Name
dribble:

#<-- End Social Media

# Build settings
markdown: kramdown
permalink: pretty
